### ISSUE TITLE
javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by raviada** [pokitdok/pokitdok-java#15]
I am using this library to access pokitdok APIs. I am on 0.9.0, added maven dependency in our spring boot application. However I am getting the following exception.
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.pokitdok.ApacheHTTPConnector.connect(ApacheHTTPConnector.java:72)
	at com.pokitdok.ApacheHTTPConnector.getAccessTokenForScope(ApacheHTTPConnector.java:192)
	at com.pokitdok.ApacheHTTPConnector.execute(ApacheHTTPConnector.java:89)
	at com.pokitdok.ApacheHTTPConnector.post(ApacheHTTPConnector.java:139)
	at com.pokitdok.ApacheHTTPConnector.post(ApacheHTTPConnector.java:126)
	at com.pokitdok.PokitDok.eligibility(PokitDok.java:320)
```

I saved cert from my browser and added it to ```truststore.jks```, still having the same issue.

Please let me know how to solve this.

**Comment by seedifferently** [comment]
Hi @raviada, thanks for using our Java client library.

We are unable to reproduce this issue, and generally this particular error has something to do with your local configuration. Perhaps an answer from this SO thread would be helpful? -- https://stackoverflow.com/q/21076179
