### ISSUE TITLE
getTradingPartners() throws ParseException

### ISSUE THREAD

**Issue by caipivara** [pokitdok/pokitdok-java#17]
- Version: `com.pokitdok:pokitdok-java:0.9`

Im getting an error `getTradingPartners()` is throwing a `ParseException`

```
Caused by: org.json.simple.parser.ParseException: null
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[json-simple-1.1.1.jar:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar:na]
        at com.pokitdok.ApacheHTTPConnector.connect(ApacheHTTPConnector.java:73) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.ApacheHTTPConnector.getAccessTokenForScope(ApacheHTTPConnector.java:192) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.ApacheHTTPConnector.execute(ApacheHTTPConnector.java:89) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.ApacheHTTPConnector.get(ApacheHTTPConnector.java:121) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.ApacheHTTPConnector.get(ApacheHTTPConnector.java:114) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.PokitDok.tradingPartners(PokitDok.java:506) ~[pokitdok-java-0.9.jar:na]
        at com.pokitdok.PokitDok.tradingPartners(PokitDok.java:529) ~[pokitdok-java-0.9.jar:na]
```

**Comment by corbinbs** [comment]
Hi @caipivara  - did that show up for you on your first attempt to interact with the API or had that client instance been in use for a while with a valid access token and then you encountered the error?

I'm trying to determine if there's a problem with token refreshing in the Java client or if there's something else going on.

**Comment by caipivara** [comment]
Yeah, I use a long living instance of the client.

**Comment by dixonwh** [comment]
Hi @caipivara We are setting up a test case to duplicate this issue. Do you know how long, approximately, it takes to receive the error? Thanks!

**Comment by caipivara** [comment]
@dixonwh not measured, it happened in milliseconds I think, or perhaps when 2 threads call the API at the same time?
